name: FLASK MYSQL CI
on:
  push:
      branches:
          - main
  pull_request:
      branches:
          - feature

permissions:
  contents: read
  pull-requests: read

env:
  FLASK_NAME: myflaskserver
  MYSQL_NAME: mydbsql
  PYTHON_VERSION: 3.12

jobs:
  flask_test:
    runs-on: ubuntu-latest
    steps:

      - name: check repo
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: git leaks
        uses: gitleaks/gitleaks-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: python setups
        uses: actions/setup-python@v7
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: "pip"
          cache-dependency-path: ./requirements.txt

      - name: Restore Pip Cache
        id: pip-cache
        uses: actions/cache@v5
        with:
          path: ~/.cache/pip
          key: pip-cache-${{ runner.os }}-${{ hashFiles('requirements.txt') }}

      - name: Display Cache Status
        run: echo "Cache Hit; ${{ steps.pip-cache.outputs.cache-hit }}"

      - name: install dependency
        run: python -m pip install -r requirements.txt

      - name: Run Pylint
        shell: bash
        run: |
          python3 -m pylint \
          $(git ls-files '*.py') \
          | tee pylint.txt

      - name: Run Pytest
        shell: bash
        run: |
          python3 -m pytest \
          test/py_test.py \
          --junitxml=results.xml

      - name: Run Flake8
        shell: bash
        run: |
          python3 -m flake8 \
          $(git ls-files '*.py') \
          | tee flake8.txt

      - name: Run Bandit
        shell: bash
        run: |
          python3 -m bandit -r . -s B101 \
          | tee bandit.txt

      - name: Run unittest
        shell: bash
        run: |
          python3 -m unittest \
          unit_test.py \
          | tee unittest.txt

      - name: Run Application
        shell: bash
        run: python3 app.py

      - name: smoke test
        run: 

      - name: Install build
        shell: bash
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install build
          python3 -m build 

      - name: upload PYLINT artifact
        uses: actions/upload-artifact@v7
        with:
          name: pylint-results
          path: pylint.txt

      - name: upload PYTEST artifact
        uses: actions/upload-artifact@v7
        with:
          name: pytest-results
          path: results.xml

      - name: upload FLAKE8 artifact
        uses: actions/upload-artifact@v7
        with:
          name: flake8-results
          path: flake8.txt

      - name: upload BANDIT artifact
        uses: actions/upload-artifact@v7
        with:
          name: bandit-results
          path: bandit.txt

      - name: upload uniitest artifact
        uses: actions/upload-artifact@v7
        with:
          name: unittest-results
          path: unittest.txt

      - name: upload BUILD artifact
        uses: actions/upload-artifact@v7
        with:
          name: python-build-results
          path: dist/