name: FLASK MYSQL CI
on:
  workflow_dispatch:
    inputs:
      environments:
        description: deployment
        required: true
        default: dev
        type: choice
        options:
          - dev
          - qa
          - prod

      app_tests:
        description: APP TESTS
        required: true
        type: boolean
        default: true

      flask_tests:
        description: FLASK TESTS
        required: true
        type: boolean
        default: true

      flask_images:
        description: FLASK IMAGE
        required: true
        type: boolean
        default: true

      mysql_images:
        description: MYSQL IMAGE
        required: true
        type: boolean
        default: true

      security_scans:
        description: SECURITY SCAN
        required: true
        type: boolean
        default: true

      smoke_tests:
        description: SMOKE TEST
        required: true
        type: boolean
        default: true

permissions:
  contents: read
  pull-requests: read

env:
  FLASK_NAME: myflaskserver
  MYSQL_NAME: mydbsql
  PYTHON_VERSION: 3.12

jobs:
  flask_test:
    runs-on: ubuntu-latest
    if: ${{ inputs.environments == 'dev' && inputs.app_tests == true }}
    steps:
      - name: calling inputs
        run: |
          echo "${{ inputs.environments }}"
          echo "${{ inputs.app_tests }}"

      - name: check repo
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: git leaks
        uses: gitleaks/gitleaks-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: python setups
        uses: actions/setup-python@v7
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: "pip"
          cache-dependency-path: ./requirements.txt

      - name: Restore Pip Cache
        id: pip-cache
        uses: actions/cache@v5
        with:
          path: ~/.cache/pip
          key: pip-cache-${{ runner.os }}-${{ hashFiles('requirements.txt') }}

      - name: Display Cache Status
        run: echo "Cache Hit; ${{ steps.pip-cache.outputs.cache-hit }}"

      - name: install dependency
        run: python -m pip install -r requirements.txt

      - name: Run Pylint
        shell: bash
        run: |
          python3 -m pylint \
          $(git ls-files '*.py') \
          | tee pylint.txt

      - name: Run Pytest
        shell: bash
        run: |
          python3 -m pytest \
          test/py_test.py \
          --junitxml=results.xml

      - name: Run Flake8
        shell: bash
        run: |
          python3 -m flake8 \
          $(git ls-files '*.py') \
          | tee flake8.txt

      - name: Run Bandit
        shell: bash
        run: |
          python3 -m bandit -r . -s B101 \
          | tee bandit.txt

      - name: Run unittest
        shell: bash
        run: |
          python3 -m unittest \
          unit_test.py \
          | tee unittest.txt

      - name: Install build
        shell: bash
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install build
          python3 -m build

      - name: upload PYLINT artifact
        uses: actions/upload-artifact@v7
        with:
          name: pylint-results
          path: pylint.txt

      - name: upload PYTEST artifact
        uses: actions/upload-artifact@v7
        with:
          name: pytest-results
          path: results.xml

      - name: upload FLAKE8 artifact
        uses: actions/upload-artifact@v7
        with:
          name: flake8-results
          path: flake8.txt

      - name: upload BANDIT artifact
        uses: actions/upload-artifact@v7
        with:
          name: bandit-results
          path: bandit.txt

      - name: upload uniitest artifact
        uses: actions/upload-artifact@v7
        with:
          name: unittest-results
          path: unittest.txt

      - name: upload BUILD artifact
        uses: actions/upload-artifact@v7
        with:
          name: python-build-results
          path: dist/

  docker_build:
    runs-on: ubuntu-latest
    if: ${{ (inputs.environments == 'dev' || inputs.environments == 'qa' || inputs.environments == 'prod') && (inputs.flask_images == true && inputs.mysql_images == true) }}
    steps:
      - name: Calling inputs
        run: |
          echo "Environment: ${{ inputs.environments }}"
          echo "Docker images: ${{ inputs.flask_images }}"

      - name: Checkout repository
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Build Flask image
        uses: docker/build-push-action@v7
        with:
          context: .
          file: ./Dockerfile.flask
          push: false
          load: true
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ env.FLASK_NAME }}:v${{ github.run_number }}-${{ github.sha }}

      - name: Build MySQL image
        uses: docker/build-push-action@v7
        with:
          context: .
          file: ./Dockerfile.database
          push: false
          load: true
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ env.MYSQL_NAME }}:v${{ github.run_number }}-${{ github.sha }}

      - name: Save Flask image
        run: docker save "${{ secrets.DOCKER_USERNAME }}/${{ env.FLASK_NAME }}:v${{ github.run_number }}-${{ github.sha }}" -o flask_image.tar

      - name: Upload Flask image
        uses: actions/upload-artifact@v7
        with:
          name: flask-image
          path: flask_image.tar

      - name: Save MySQL image
        run: |
          docker save "${{ secrets.DOCKER_USERNAME }}/${{ env.MYSQL_NAME }}:v${{ github.run_number }}-${{ github.sha }}" -o mysql_image.tar

      - name: Upload MySQL image
        uses: actions/upload-artifact@v7
        with:
          name: mysql-image
          path: mysql_image.tar

  docker_security_scan:
    needs: docker_build
    runs-on: ubuntu-latest
    if: ${{ (inputs.environments == 'qa' || inputs.environments == 'prod') && inputs.security_scans == true }}
    steps:
      - name: check repo
        uses: actions/checkout@v7
        with:
          fetch-depth: 0
      - name: calling inputs
        run: |
          echo "${{ inputs.environments }}"
          echo "${{ inputs.security_scans }}"

      - name: download flask artifact
        uses: actions/download-artifact@v7
        with:
          name: flask-image

      - name: unzip and load flask-image
        run: docker load -i flask_image.tar

      - name: download mysql artifact
        uses: actions/download-artifact@v7
        with:
          name: mysql-image

      - name: unzip and load mysql-image
        run: docker load -i mysql_image.tar

      - name: flask image secrets scan
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          scan-type: config
          scan-ref: ./Dockerfile.flask
          format: "table"
          vuln-type: "os,library"
          scanners: "secret"
          ignore-unfixed: "true"
          severity: "CRITICAL"
          exit-code: "1"
          output: flask_secrets.txt

      - name: mysql image secrets scan
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          scan-type: config
          scan-ref: ./Dockerfile.database
          format: "table"
          vuln-type: "os,library"
          scanners: "secret"
          ignore-unfixed: "true"
          severity: "CRITICAL"
          exit-code: 1
          output: mysql_secrets.txt

      - name: flask image vuln scan
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          image-ref: ${{ secrets.DOCKER_USERNAME }}/${{ env.FLASK_NAME }}:v${{ github.run_number }}-${{ github.sha }}
          format: "table"
          vuln-type: "os,library"
          scanners: "vuln"
          ignore-unfixed: "true"
          severity: "CRITICAL"
          exit-code: 1
          output: flask_vuln.txt

      - name: mysql image vuln scan
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          image-ref: ${{ secrets.DOCKER_USERNAME }}/${{ env.MYSQL_NAME }}:v${{ github.run_number }}-${{ github.sha }}
          format: "table"
          vuln-type: "os,library"
          scanners: "vuln"
          ignore-unfixed: "true"
          severity: "CRITICAL"
          exit-code: 1
          output: mysql_vuln.txt

      - name: flask secret artifact
        uses: actions/upload-artifact@v7
        with:
          name: flask_secrets
          path: flask_secrets.txt

      - name: mysql secret artifact
        uses: actions/upload-artifact@v7
        with:
          name: mysql_secrets
          path: mysql_secrets.txt

      - name: flask vuln artifact
        uses: actions/upload-artifact@v7
        with:
          name: flask_vuln
          path: flask_vuln.txt

      - name: mysq vuln artifact
        uses: actions/upload-artifact@v7
        with:
          name: mysq_vuln
          path: mysq_vuln.txt

  deployment:
    needs:
      - docker_build
      - docker_security_scan
    runs-on: ubuntu-latest
    if: ${{ inputs.environments == 'prod' && inputs.smoke_tests == true }}
    steps:
      - name: calling inputs
        run: |
          echo "${{ inputs.environments }}"
          echo "${{ inputs.smoke_tests }}"

      - name: download flask artifact
        uses: actions/download-artifact@v7
        with:
          name: flask-image

      - name: unzip and load flask-image
        run: docker load -i flask_image.tar

      - name: download mysql artifact
        uses: actions/download-artifact@v7
        with:
          name: mysql-image

      - name: unzip and load mysql-image
        run: docker load -i mysql_image.tar

      - name: docker network
        run: docker network create --driver bridge mynetwork

      - name: docker volume
        run: docker volume create myvolume

      - name: flask container
        run: docker run -d -p 5000:5000 --network mynetwork --name myflaskserver ${{ secrets.DOCKER_USERNAME }}/${{ env.FLASK_NAME }}:v${{ github.run_number }}-${{ github.sha }}

      - run: sleep 10

      - name: mysql container
        run: docker run -d -p 3306:3306 --network mynetwork -v myvolume:/db/schema --name mydbsql ${{ secrets.DOCKER_USERNAME }}/${{ env.MYSQL_NAME }}:v${{ github.run_number }}-${{ github.sha }}

      - run: sleep 10

      - name: flask image smoke test
        run: curl --fail --retry-10 http://localhost:5000/health >> flask_smoke_test.txt

      - name: mysql image smoke test
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
        run: |
          docker exec mydbsql \
          mysqladmin ping \
          -h 127.0.0.1 \
          -u root \
          -p"$MYSQL_ROOT_PASSWORD" \
          --silent >> mysql_smoke_test.txt

      - name: flask container fails
        if: ${{ failure() }}
        run: docker logs myflaskserver >> flask_faillogs.txt

      - name: mysql container fails
        if: ${{ failure() }}
        run: docker logs mydbsql >> mysql_faillogs.txt

      - name: remove containers
        if: ${{ always() }}
        run: |
          docker rm -f mysever
          docker rm -f mydbsql
          docker network rm mynetwork

      - name: upload flask smoke test result
        uses: actions/upload-artifact@v7
        with:
          name: flask_smoke_test
          path: flask_smoke_test.txt

      - name: upload mysql smoke test result
        uses: actions/upload-artifact@v7
        with:
          name: mysql_smoke_test
          path: mysql_smoke_test.txt

      - name: upload flask container logs
        uses: actions/upload-artifact@v7
        with:
          name: flask_faillogs
          path: flask_faillogs.txt

      - name: upload mysql container logs
        uses: actions/upload-artifact@v7
        with:
          name: mysql_faillogs
          path: mysql_faillogs.txt

  production:
    needs:
      - docker_build
      - docker_security_scan
      - deployment
    runs-on: ubuntu-latest
    if: ${{ inputs.environments == 'prod' }}
    steps:
      - name: re-use workflow call
        uses: ./.github/workflows/workflow_call_ci.yaml
        with:
          application_name: flask mysql app
          docker_compose: true
          replicas: true
